id: P003146
initial_creation_type: ocr
created_at: 28/03/2020
last_modified_at: 24/11/2021
source_metadata:
  id: bdr:W1KG4277
  title: དཔལ་འབྲུག་པའི་ཟབ་ཁྲིད་ཕྱོགས་བསྡེབས
  author: ''
  volumes:
    e3b1fce657d7402e88a671070d759fec:
      image_group_id: I1PD100449
      title: ''
      volume_number: 1
      total_pages: 668
      base_file: v001.txt
    6af5bb2d26374c9f9158793b805af3cf:
      image_group_id: I1PD100450
      title: ''
      volume_number: 2
      total_pages: 672
      base_file: v002.txt
    89c0f4c159b447af9486bb2c2c8e7bda:
      image_group_id: I1PD100451
      title: ''
      volume_number: 3
      total_pages: 616
      base_file: v003.txt
    a5b2660a8ae548d7ae49a12a481b85fa:
      image_group_id: I1PD100452
      title: ''
      volume_number: 4
      total_pages: 624
      base_file: v004.txt
    7c34e160931a48e9a780eeda5edb185e:
      image_group_id: I1PD100453
      title: ''
      volume_number: 5
      total_pages: 608
      base_file: v005.txt
