id: I9B2413A4
legacy_id: P003146
ocr_import_info:
  bdrc_scan_id: W1KG4277
  source: bdrc
  ocr_info:
    timestamp: '2020-03-28T16:05:36'
    imagesfolder: images
  batch_id: batch001
  software_id: vision
  expected_default_language: bo
  op_import_options: {}
  op_import_version: 1.0.0
default_language: bo
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2022-08-31T15:29:55.788822+00:00'
last_modified: 2022-08-31 23:31:04.780978
parser: https://github.com/OpenPecha/Toolkit/blob/7f57883d84bc10351527a49ee6ce970ace404e50/openpecha/formatters/google_ocr.py
source_metadata:
  id: http://purl.bdrc.io/resource/W1KG4277
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  reproduction_of: http://purl.bdrc.io/resource/MW1KG4277
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: དཔལ་འབྲུག་པའི་ཟབ་ཁྲིད་ཕྱོགས་བསྡེབས།
statistics:
  ocr_word_mean_confidence_index: 0.8720673594154661
  ocr_word_median_confidence_index: 0.9599999785423279
quality: null
bases:
  I1PD100450:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1PD100450
      total_pages: 672
      volume_number: 2
      volume_pages_bdrc_intro: 2
    order: 2
    base_file: I1PD100450.txt
    statistics:
      ocr_word_median_confidence_index: 0.9599999785423279
      ocr_word_mean_confidence_index: 0.8849955319400774
    legacy_id: v002
  I1PD100451:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1PD100451
      total_pages: 616
      volume_number: 3
      volume_pages_bdrc_intro: 2
    order: 3
    base_file: I1PD100451.txt
    statistics:
      ocr_word_median_confidence_index: 0.9399999976158142
      ocr_word_mean_confidence_index: 0.8584391538729034
    legacy_id: v003
  I1PD100453:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1PD100453
      total_pages: 608
      volume_number: 5
      volume_pages_bdrc_intro: 2
    order: 5
    base_file: I1PD100453.txt
    statistics:
      ocr_word_median_confidence_index: 0.949999988079071
      ocr_word_mean_confidence_index: 0.857747341063122
    legacy_id: v005
  I1PD100449:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1PD100449
      total_pages: 668
      volume_number: 1
      volume_pages_bdrc_intro: 2
    order: 1
    base_file: I1PD100449.txt
    statistics:
      ocr_word_median_confidence_index: 0.949999988079071
      ocr_word_mean_confidence_index: 0.8758781326383424
    legacy_id: v001
  I1PD100452:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1PD100452
      total_pages: 624
      volume_number: 4
      volume_pages_bdrc_intro: 2
    order: 4
    base_file: I1PD100452.txt
    statistics:
      ocr_word_median_confidence_index: 0.9599999785423279
      ocr_word_mean_confidence_index: 0.878447345310225
    legacy_id: v004
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
