id: I9B2413A4
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-28T16:09:56+00:00'
last_modified: '2022-06-07T17:54:15.296793+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1KG4277
  title: དཔལ་འབྲུག་པའི་ཟབ་ཁྲིད་ཕྱོགས་བསྡེབས
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    5CCC:
      image_group_id: I1PD100449
      title: ''
      total_pages: 668
      order: 1
      base_file: 5CCC.txt
    '7888':
      image_group_id: I1PD100450
      title: ''
      total_pages: 672
      order: 2
      base_file: 7888.txt
    AD42:
      image_group_id: I1PD100451
      title: ''
      total_pages: 616
      order: 3
      base_file: AD42.txt
    4C47:
      image_group_id: I1PD100452
      title: ''
      total_pages: 624
      order: 4
      base_file: 4C47.txt
    D93B:
      image_group_id: I1PD100453
      title: ''
      total_pages: 608
      order: 5
      base_file: D93B.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
